CREATE TYPE "Role" AS ENUM ('PATIENT','PHARMACY','ADMIN');
CREATE TYPE "RequestStatus" AS ENUM ('OPEN','FULFILLED','EXPIRED','CANCELLED');
CREATE TYPE "ResponseStatus" AS ENUM ('AVAILABLE','NOT_AVAILABLE','CAN_ORDER');
CREATE TYPE "ReservationStatus" AS ENUM ('ACTIVE','PICKED_UP','CANCELLED','EXPIRED');
CREATE TABLE "User"("id" TEXT NOT NULL,"name" TEXT NOT NULL,"phone" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"role" "Role" NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"tokenVersion" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "User_pkey" PRIMARY KEY("id"));
CREATE TABLE "Session"("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"tokenHash" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Session_pkey" PRIMARY KEY("id"));
CREATE TABLE "Medicine"("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"name" TEXT NOT NULL,"dose" TEXT NOT NULL,"quantity" INTEGER NOT NULL,"remaining" INTEGER NOT NULL,"dosesPerDay" DOUBLE PRECISION NOT NULL,"nextRefillDate" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Medicine_pkey" PRIMARY KEY("id"));
CREATE TABLE "Pharmacy"("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"name" TEXT NOT NULL,"address" TEXT NOT NULL,"lat" DOUBLE PRECISION NOT NULL,"lng" DOUBLE PRECISION NOT NULL,"verified" BOOLEAN NOT NULL DEFAULT false,"verificationNote" TEXT,CONSTRAINT "Pharmacy_pkey" PRIMARY KEY("id"));
CREATE TABLE "Inventory"("id" TEXT NOT NULL,"pharmacyId" TEXT NOT NULL,"medicineName" TEXT NOT NULL,"quantity" INTEGER NOT NULL DEFAULT 0,"unitPrice" DOUBLE PRECISION NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Inventory_pkey" PRIMARY KEY("id"));
CREATE TABLE "MedicineRequest"("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"medicineId" TEXT NOT NULL,"quantity" INTEGER NOT NULL,"lat" DOUBLE PRECISION NOT NULL,"lng" DOUBLE PRECISION NOT NULL,"status" "RequestStatus" NOT NULL DEFAULT 'OPEN',"activeKey" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"expiresAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "MedicineRequest_pkey" PRIMARY KEY("id"));
CREATE TABLE "AvailabilityResponse"("id" TEXT NOT NULL,"requestId" TEXT NOT NULL,"pharmacyId" TEXT NOT NULL,"status" "ResponseStatus" NOT NULL,"price" DOUBLE PRECISION,"note" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "AvailabilityResponse_pkey" PRIMARY KEY("id"));
CREATE TABLE "Reservation"("id" TEXT NOT NULL,"requestId" TEXT NOT NULL,"pharmacyId" TEXT NOT NULL,"userId" TEXT NOT NULL,"quantity" INTEGER NOT NULL,"unitPrice" DOUBLE PRECISION NOT NULL,"totalPrice" DOUBLE PRECISION NOT NULL,"status" "ReservationStatus" NOT NULL DEFAULT 'ACTIVE',"activeKey" TEXT,"expiresAt" TIMESTAMP(3) NOT NULL,"stockRestoredAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"pickedUpAt" TIMESTAMP(3),CONSTRAINT "Reservation_pkey" PRIMARY KEY("id"));
CREATE TABLE "Notification"("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"title" TEXT NOT NULL,"body" TEXT NOT NULL,"data" JSONB,"readAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Notification_pkey" PRIMARY KEY("id"));
CREATE TABLE "PushToken"("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"token" TEXT NOT NULL,"platform" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "PushToken_pkey" PRIMARY KEY("id"));
CREATE TABLE "AuditLog"("id" TEXT NOT NULL,"actorUserId" TEXT,"action" TEXT NOT NULL,"entity" TEXT NOT NULL,"entityId" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuditLog_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "User_phone_key" ON "User"("phone");
CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash");
CREATE UNIQUE INDEX "Pharmacy_userId_key" ON "Pharmacy"("userId");
CREATE UNIQUE INDEX "Inventory_pharmacyId_medicineName_key" ON "Inventory"("pharmacyId","medicineName");
CREATE UNIQUE INDEX "MedicineRequest_activeKey_key" ON "MedicineRequest"("activeKey");
CREATE UNIQUE INDEX "AvailabilityResponse_requestId_pharmacyId_key" ON "AvailabilityResponse"("requestId","pharmacyId");
CREATE UNIQUE INDEX "Reservation_activeKey_key" ON "Reservation"("activeKey");
CREATE UNIQUE INDEX "PushToken_token_key" ON "PushToken"("token");
CREATE INDEX "Session_userId_revokedAt_idx" ON "Session"("userId","revokedAt");
CREATE INDEX "Medicine_userId_nextRefillDate_idx" ON "Medicine"("userId","nextRefillDate");
CREATE INDEX "Pharmacy_verified_idx" ON "Pharmacy"("verified");
CREATE INDEX "Inventory_medicineName_idx" ON "Inventory"("medicineName");
CREATE INDEX "MedicineRequest_userId_status_createdAt_idx" ON "MedicineRequest"("userId","status","createdAt");
CREATE INDEX "MedicineRequest_status_expiresAt_idx" ON "MedicineRequest"("status","expiresAt");
CREATE INDEX "AvailabilityResponse_pharmacyId_status_idx" ON "AvailabilityResponse"("pharmacyId","status");
CREATE INDEX "Reservation_userId_status_createdAt_idx" ON "Reservation"("userId","status","createdAt");
CREATE INDEX "Reservation_pharmacyId_status_createdAt_idx" ON "Reservation"("pharmacyId","status","createdAt");
CREATE INDEX "Reservation_status_expiresAt_idx" ON "Reservation"("status","expiresAt");
CREATE INDEX "Notification_userId_readAt_createdAt_idx" ON "Notification"("userId","readAt","createdAt");
CREATE INDEX "PushToken_userId_idx" ON "PushToken"("userId");
CREATE INDEX "AuditLog_actorUserId_createdAt_idx" ON "AuditLog"("actorUserId","createdAt");
CREATE INDEX "AuditLog_entity_entityId_createdAt_idx" ON "AuditLog"("entity","entityId","createdAt");
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Medicine" ADD CONSTRAINT "Medicine_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Pharmacy" ADD CONSTRAINT "Pharmacy_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Inventory" ADD CONSTRAINT "Inventory_pharmacyId_fkey" FOREIGN KEY("pharmacyId") REFERENCES "Pharmacy"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MedicineRequest" ADD CONSTRAINT "MedicineRequest_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MedicineRequest" ADD CONSTRAINT "MedicineRequest_medicineId_fkey" FOREIGN KEY("medicineId") REFERENCES "Medicine"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AvailabilityResponse" ADD CONSTRAINT "AvailabilityResponse_requestId_fkey" FOREIGN KEY("requestId") REFERENCES "MedicineRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AvailabilityResponse" ADD CONSTRAINT "AvailabilityResponse_pharmacyId_fkey" FOREIGN KEY("pharmacyId") REFERENCES "Pharmacy"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_requestId_fkey" FOREIGN KEY("requestId") REFERENCES "MedicineRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_pharmacyId_fkey" FOREIGN KEY("pharmacyId") REFERENCES "Pharmacy"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PushToken" ADD CONSTRAINT "PushToken_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorUserId_fkey" FOREIGN KEY("actorUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;