CREATE TYPE "SubscriptionStatus" AS ENUM ('TRIALING','ACTIVE','PAST_DUE','CANCELLED','EXPIRED');
CREATE TYPE "PlanType" AS ENUM ('CONSUMER_PREMIUM','PHARMACY_PRO');
CREATE TYPE "FamilyRole" AS ENUM ('FAMILY','CAREGIVER');
CREATE TYPE "DocumentType" AS ENUM ('PRESCRIPTION','PHARMACY_LICENSE');
CREATE TABLE "Subscription"("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"plan" "PlanType" NOT NULL,"status" "SubscriptionStatus" NOT NULL,"provider" TEXT NOT NULL,"providerCustomerId" TEXT,"providerSubscriptionId" TEXT,"currentPeriodStart" TIMESTAMP(3),"currentPeriodEnd" TIMESTAMP(3),"trialEndsAt" TIMESTAMP(3),"cancelAtPeriodEnd" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Subscription_pkey" PRIMARY KEY("id"));
CREATE TABLE "FamilyMember"("id" TEXT NOT NULL,"ownerId" TEXT NOT NULL,"memberId" TEXT NOT NULL,"role" "FamilyRole" NOT NULL,"canViewMedicines" BOOLEAN NOT NULL DEFAULT true,"canCreateRefillRequest" BOOLEAN NOT NULL DEFAULT true,"canViewHistory" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "FamilyMember_pkey" PRIMARY KEY("id"));
CREATE TABLE "UserDocument"("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"type" "DocumentType" NOT NULL,"storageKey" TEXT NOT NULL,"originalName" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"sizeBytes" INTEGER NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "UserDocument_pkey" PRIMARY KEY("id"));
CREATE TABLE "Reminder"("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"medicineId" TEXT NOT NULL,"hour" INTEGER NOT NULL,"minute" INTEGER NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT true,"timezone" TEXT NOT NULL DEFAULT 'Asia/Kolkata',"advanced" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Reminder_pkey" PRIMARY KEY("id"));
CREATE TABLE "TravelMode"("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT false,"startDate" TIMESTAMP(3),"endDate" TIMESTAMP(3),"timezone" TEXT,"notes" TEXT,CONSTRAINT "TravelMode_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "Subscription_providerSubscriptionId_key" ON "Subscription"("providerSubscriptionId");
CREATE UNIQUE INDEX "FamilyMember_ownerId_memberId_key" ON "FamilyMember"("ownerId","memberId");
CREATE UNIQUE INDEX "TravelMode_userId_key" ON "TravelMode"("userId");
CREATE INDEX "Subscription_userId_status_idx" ON "Subscription"("userId","status");
CREATE INDEX "UserDocument_userId_type_createdAt_idx" ON "UserDocument"("userId","type","createdAt");
CREATE INDEX "Reminder_userId_enabled_idx" ON "Reminder"("userId","enabled");
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FamilyMember" ADD CONSTRAINT "FamilyMember_ownerId_fkey" FOREIGN KEY("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FamilyMember" ADD CONSTRAINT "FamilyMember_memberId_fkey" FOREIGN KEY("memberId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserDocument" ADD CONSTRAINT "UserDocument_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Reminder" ADD CONSTRAINT "Reminder_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Reminder" ADD CONSTRAINT "Reminder_medicineId_fkey" FOREIGN KEY("medicineId") REFERENCES "Medicine"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TravelMode" ADD CONSTRAINT "TravelMode_userId_fkey" FOREIGN KEY("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
