import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import crypto from 'node:crypto';
import { PrismaClient, Prisma, Role, ResponseStatus, RequestStatus, ReservationStatus, FamilyRole } from '@prisma/client';
import { z } from 'zod';
import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';

const db = new PrismaClient();
const app = express();
const PORT = Number(process.env.PORT ?? 4000);
const JWT_SECRET = process.env.JWT_SECRET ?? '';
if (JWT_SECRET.length < 32) throw new Error('JWT_SECRET must be at least 32 characters');
const REQUEST_RADIUS_KM = Number(process.env.REQUEST_RADIUS_KM ?? 25);
const REQUEST_TTL_HOURS = Number(process.env.REQUEST_TTL_HOURS ?? 24);
const RESERVATION_TTL_HOURS = Number(process.env.RESERVATION_TTL_HOURS ?? 4);

app.disable('x-powered-by');
app.set('trust proxy', process.env.TRUST_PROXY === '1' ? 1 : false);
app.use(helmet({contentSecurityPolicy:false}));
const allowedOrigins = (process.env.CORS_ORIGIN ?? 'http://localhost:8081').split(',').map(x=>x.trim()).filter(Boolean);
app.use(cors({origin:(origin,cb)=>!origin || allowedOrigins.includes('*') || allowedOrigins.includes(origin)?cb(null,true):cb(new Error('CORS origin denied'))}));
app.use(express.json({limit:'1mb'}));
const generalLimiter=rateLimit({windowMs:60_000,limit:120,standardHeaders:true,legacyHeaders:false});
const authLimiter=rateLimit({windowMs:15*60_000,limit:30,standardHeaders:true,legacyHeaders:false});
app.use(generalLimiter);

const phone=z.string().regex(/^[6-9]\d{9}$/);
const id=z.string().min(1).max(100);
type Req=express.Request & {auth?:{userId:string;role:Role;sessionId:string}};
const hash=(v:string)=>crypto.createHash('sha256').update(v).digest('hex');
const publicUser=(u:any)=>({id:u.id,name:u.name,phone:u.phone,role:u.role,active:u.active,pharmacy:u.pharmacy??null});
function distanceKm(aLat:number,aLng:number,bLat:number,bLng:number){const R=6371,r=Math.PI/180,dLat=(bLat-aLat)*r,dLng=(bLng-aLng)*r;const x=Math.sin(dLat/2)**2+Math.cos(aLat*r)*Math.cos(bLat*r)*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function daysRemaining(remaining:number,doses:number){if(!Number.isFinite(remaining)||!Number.isFinite(doses)||doses<=0)return 0;return remaining<=0?0:Math.ceil(remaining/doses);}
function sign(userId:string,role:Role,sessionId:string){return jwt.sign({sub:userId,role,sid:sessionId},JWT_SECRET,{expiresIn:'7d'});}
async function createSession(userId:string,role:Role){const raw=crypto.randomBytes(32).toString('hex');const s=await db.session.create({data:{userId,tokenHash:hash(raw),expiresAt:new Date(Date.now()+7*86400000)}});return sign(userId,role,s.id)+'.'+raw;}
async function auth(req:Req,res:express.Response,next:express.NextFunction){try{const raw=req.headers.authorization?.startsWith('Bearer ')?req.headers.authorization.slice(7):'';if(!raw)return res.status(401).json({error:'Authentication required'});const cut=raw.lastIndexOf('.');const jwtPart=cut>0?raw.slice(0,cut):'';const sessionSecret=cut>0?raw.slice(cut+1):'';if(!jwtPart||!sessionSecret)throw new Error('bad token');const p=jwt.verify(jwtPart,JWT_SECRET) as any;const s=await db.session.findUnique({where:{id:p.sid},include:{user:true}});if(!s||s.revokedAt||s.expiresAt<new Date()||s.tokenHash!==hash(sessionSecret)||!s.user.active)throw new Error('session invalid');req.auth={userId:s.user.id,role:s.user.role,sessionId:s.id};next();}catch{return res.status(401).json({error:'Invalid or expired session'});}}
function roles(...allowed:Role[]){return (req:Req,res:express.Response,next:express.NextFunction)=>req.auth&&allowed.includes(req.auth.role)?next():res.status(403).json({error:'Forbidden'});}
async function audit(actorUserId:string|undefined,action:string,entity:string,entityId?:string,metadata?:unknown){try{await db.auditLog.create({data:{actorUserId,action,entity,entityId,metadata:metadata as Prisma.InputJsonValue}});}catch(e){console.error('audit failure',e);}}
async function notify(userId:string,title:string,body:string,data:Record<string,unknown>={}){const n=await db.notification.create({data:{userId,title,body,data}});const tokens=await db.pushToken.findMany({where:{userId}});if(tokens.length===0)return n;const messages=tokens.map(t=>({to:t.token,title,body,data,sound:'default'}));try{const r=await fetch('https://exp.host/--/api/v2/push/send',{method:'POST',headers:{'content-type':'application/json',...(process.env.EXPO_ACCESS_TOKEN?{Authorization:`Bearer ${process.env.EXPO_ACCESS_TOKEN}`}:{})},body:JSON.stringify(messages)});if(!r.ok)console.error('Expo push failed',r.status,await r.text());}catch(e){console.error('Expo push error',e);}return n;}
async function restoreStock(tx:Prisma.TransactionClient,r:any){if(r.stockRestoredAt)return;const req=await tx.medicineRequest.findUnique({where:{id:r.requestId},include:{medicine:true}});if(!req)return;const restored=await tx.inventory.updateMany({where:{pharmacyId:r.pharmacyId,medicineName:req.medicine.name},data:{quantity:{increment:r.quantity}}});if(restored.count!==1)throw new Error('Inventory record missing; cannot restore stock');await tx.reservation.update({where:{id:r.id},data:{stockRestoredAt:new Date(),activeKey:null}});}
async function expire(){const now=new Date();const expiredReq=await db.medicineRequest.findMany({where:{status:RequestStatus.OPEN,expiresAt:{lt:now}},select:{id:true,userId:true,medicineId:true}});for(const r of expiredReq){await db.medicineRequest.updateMany({where:{id:r.id,status:RequestStatus.OPEN},data:{status:RequestStatus.EXPIRED,activeKey:null}});await notify(r.userId,'Request expired','Your medicine request expired.');}
 const expired=await db.reservation.findMany({where:{status:ReservationStatus.ACTIVE,expiresAt:{lt:now}}});for(const r of expired){await db.$transaction(async tx=>{const cur=await tx.reservation.findUnique({where:{id:r.id}});if(!cur||cur.status!==ReservationStatus.ACTIVE)return;await restoreStock(tx,cur);await tx.reservation.update({where:{id:r.id},data:{status:ReservationStatus.EXPIRED,activeKey:null}});const req=await tx.medicineRequest.findUnique({where:{id:r.requestId}});if(req)await tx.medicineRequest.update({where:{id:req.id},data:{status:RequestStatus.OPEN,activeKey:`${req.userId}:${req.medicineId}`}});});await notify(r.userId,'Reservation expired','Your reservation expired and the medicine was released.');}}

app.get('/health',(_req,res)=>res.json({ok:true,service:'medbridge-api',time:new Date().toISOString()}));
app.get('/ready',async(_req,res)=>{try{await db.$queryRaw`SELECT 1`;res.json({ready:true});}catch{res.status(503).json({ready:false});}});

app.post('/auth/register',authLimiter,async(req,res,next)=>{try{const p=z.object({name:z.string().trim().min(2).max(80),phone,password:z.string().min(8).max(72),role:z.enum(['PATIENT','PHARMACY']).default('PATIENT'),pharmacy:z.object({name:z.string().trim().min(2).max(120),address:z.string().trim().min(3).max(250),lat:z.number().gte(-90).lte(90),lng:z.number().gte(-180).lte(180)}).optional()}).parse(req.body);if(p.role==='PHARMACY'&&!p.pharmacy)throw new Error('Pharmacy details required');if(await db.user.findUnique({where:{phone:p.phone}}))return res.status(409).json({error:'Phone already registered'});const u=await db.user.create({data:{name:p.name,phone:p.phone,passwordHash:await bcrypt.hash(p.password,12),role:p.role as Role,pharmacy:p.pharmacy?{create:{...p.pharmacy}}:undefined},include:{pharmacy:true}});const token=await createSession(u.id,u.role);res.status(201).json({token,user:publicUser(u)});}catch(e){next(e)}});
app.post('/auth/login',authLimiter,async(req,res,next)=>{try{const p=z.object({phone,password:z.string().min(1)}).parse(req.body);const u=await db.user.findUnique({where:{phone:p.phone},include:{pharmacy:true}});if(!u||!u.active||!(await bcrypt.compare(p.password,u.passwordHash)))return res.status(401).json({error:'Invalid credentials'});const token=await createSession(u.id,u.role);res.json({token,user:publicUser(u)});}catch(e){next(e)}});
app.post('/auth/logout',auth,async(req:Req,res)=>{await db.session.update({where:{id:req.auth!.sessionId},data:{revokedAt:new Date()}});res.status(204).send();});
app.post('/auth/change-password',auth,async(req:Req,res,next)=>{try{const p=z.object({currentPassword:z.string().min(1),newPassword:z.string().min(8).max(72)}).parse(req.body);const u=await db.user.findUnique({where:{id:req.auth!.userId}});if(!u||!(await bcrypt.compare(p.currentPassword,u.passwordHash)))return res.status(400).json({error:'Current password is incorrect'});await db.user.update({where:{id:u.id},data:{passwordHash:await bcrypt.hash(p.newPassword,12),tokenVersion:{increment:1}}});await db.session.updateMany({where:{userId:u.id},data:{revokedAt:new Date()}});await audit(u.id,'PASSWORD_CHANGED','USER',u.id);res.json({ok:true});}catch(e){next(e)}});
app.get('/me',auth,async(req:Req,res)=>{const u=await db.user.findUnique({where:{id:req.auth!.userId},include:{pharmacy:true}});if(!u)return res.status(404).json({error:'User not found'});res.json(publicUser(u));});
app.patch('/me',auth,async(req:Req,res,next)=>{try{const p=z.object({name:z.string().trim().min(2).max(80)}).parse(req.body);const u=await db.user.update({where:{id:req.auth!.userId},data:{name:p.name},include:{pharmacy:true}});await audit(u.id,'PROFILE_UPDATED','USER',u.id);res.json(publicUser(u));}catch(e){next(e)}});

app.get('/medicines',auth,roles(Role.PATIENT),async(req:Req,res)=>{const ms=await db.medicine.findMany({where:{userId:req.auth!.userId},orderBy:{nextRefillDate:'asc'}});res.json(ms.map(m=>({...m,daysRemaining:daysRemaining(m.remaining,m.dosesPerDay)})));});
app.post('/medicines',auth,roles(Role.PATIENT),async(req:Req,res,next)=>{try{const p=z.object({name:z.string().trim().min(2).max(120),dose:z.string().trim().min(1).max(80),quantity:z.number().int().positive().max(100000),remaining:z.number().int().min(0),dosesPerDay:z.number().positive().max(100)}).parse(req.body);if(p.remaining>p.quantity)return res.status(400).json({error:'Remaining cannot exceed quantity'});const m=await db.medicine.create({data:{...p,userId:req.auth!.userId,nextRefillDate:new Date(Date.now()+daysRemaining(p.remaining,p.dosesPerDay)*86400000)}});await audit(req.auth!.userId,'MEDICINE_CREATED','MEDICINE',m.id);res.status(201).json(m);}catch(e){next(e)}});
app.patch('/medicines/:id',auth,roles(Role.PATIENT),async(req:Req,res,next)=>{try{const p=z.object({name:z.string().trim().min(2).max(120).optional(),dose:z.string().trim().min(1).max(80).optional(),remaining:z.number().int().min(0).optional(),quantity:z.number().int().positive().max(100000).optional(),dosesPerDay:z.number().positive().max(100).optional()}).parse(req.body);const old=await db.medicine.findFirst({where:{id:req.params.id,userId:req.auth!.userId}});if(!old)return res.status(404).json({error:'Medicine not found'});const remaining=p.remaining??old.remaining,quantity=p.quantity??old.quantity,doses=p.dosesPerDay??old.dosesPerDay;if(remaining>quantity)return res.status(400).json({error:'Remaining cannot exceed quantity'});const m=await db.medicine.update({where:{id:old.id},data:{...p,nextRefillDate:new Date(Date.now()+daysRemaining(remaining,doses)*86400000)}});await audit(req.auth!.userId,'MEDICINE_UPDATED','MEDICINE',m.id);res.json(m);}catch(e){next(e)}});
app.delete('/medicines/:id',auth,roles(Role.PATIENT),async(req:Req,res)=>{const m=await db.medicine.findFirst({where:{id:req.params.id,userId:req.auth!.userId}});if(!m)return res.status(404).json({error:'Medicine not found'});await db.medicine.delete({where:{id:m.id}});await audit(req.auth!.userId,'MEDICINE_DELETED','MEDICINE',m.id);res.status(204).send();});

app.post('/requests',auth,roles(Role.PATIENT),async(req:Req,res,next)=>{try{await expire();const p=z.object({medicineId:id,quantity:z.number().int().positive().max(100000),lat:z.number().gte(-90).lte(90),lng:z.number().gte(-180).lte(180)}).parse(req.body);const med=await db.medicine.findFirst({where:{id:p.medicineId,userId:req.auth!.userId}});if(!med)return res.status(404).json({error:'Medicine not found'});const activeKey=`${req.auth!.userId}:${med.id}`;try{const r=await db.medicineRequest.create({data:{userId:req.auth!.userId,medicineId:med.id,quantity:p.quantity,lat:p.lat,lng:p.lng,activeKey,expiresAt:new Date(Date.now()+REQUEST_TTL_HOURS*3600000)}});await audit(req.auth!.userId,'REQUEST_CREATED','REQUEST',r.id,{quantity:p.quantity});res.status(201).json(r);}catch(e:any){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2002')return res.status(409).json({error:'An active request already exists for this medicine'});throw e;}}catch(e){next(e)}});
app.get('/requests',auth,roles(Role.PATIENT),async(req:Req,res)=>{await expire();const rs=await db.medicineRequest.findMany({where:{userId:req.auth!.userId},include:{medicine:true,responses:{include:{pharmacy:true}},reservations:{include:{pharmacy:true}}},orderBy:{createdAt:'desc'},take:100});res.json(rs);});
app.get('/requests/:id',auth,async(req:Req,res)=>{await expire();const r=await db.medicineRequest.findUnique({where:{id:req.params.id},include:{medicine:true,responses:{include:{pharmacy:true}},reservations:{include:{pharmacy:true}}}});if(!r)return res.status(404).json({error:'Request not found'});if(r.userId!==req.auth!.userId&&req.auth!.role!==Role.ADMIN)return res.status(403).json({error:'Forbidden'});res.json(r);});
app.post('/requests/:id/cancel',auth,roles(Role.PATIENT),async(req:Req,res)=>{const r=await db.medicineRequest.findFirst({where:{id:req.params.id,userId:req.auth!.userId}});if(!r)return res.status(404).json({error:'Request not found'});if(r.status!==RequestStatus.OPEN)return res.status(400).json({error:'Only open requests can be cancelled'});const u=await db.medicineRequest.update({where:{id:r.id},data:{status:RequestStatus.CANCELLED,activeKey:null}});await audit(req.auth!.userId,'REQUEST_CANCELLED','REQUEST',r.id);res.json(u);});

app.get('/pharmacies/nearby',auth,roles(Role.PATIENT),async(req,res,next)=>{try{const q=z.object({lat:z.coerce.number().gte(-90).lte(90),lng:z.coerce.number().gte(-180).lte(180),radiusKm:z.coerce.number().positive().max(100).default(REQUEST_RADIUS_KM)}).parse(req.query);const ps=await db.pharmacy.findMany({where:{verified:true},select:{id:true,name:true,address:true,lat:true,lng:true}});res.json(ps.map(p=>({...p,distanceKm:distanceKm(q.lat,q.lng,p.lat,p.lng)})).filter(p=>p.distanceKm<=q.radiusKm).sort((a,b)=>a.distanceKm-b.distanceKm));}catch(e){next(e)}});

app.get('/pharmacy/profile',auth,roles(Role.PHARMACY),async(req:Req,res)=>{const p=await db.pharmacy.findUnique({where:{userId:req.auth!.userId}});if(!p)return res.status(404).json({error:'Pharmacy profile missing'});res.json(p);});
app.patch('/pharmacy/profile',auth,roles(Role.PHARMACY),async(req:Req,res,next)=>{try{const p=z.object({name:z.string().trim().min(2).max(120),address:z.string().trim().min(3).max(250),lat:z.number().gte(-90).lte(90),lng:z.number().gte(-180).lte(180)}).parse(req.body);const ph=await db.pharmacy.findUnique({where:{userId:req.auth!.userId}});if(!ph)return res.status(404).json({error:'Pharmacy profile missing'});const u=await db.pharmacy.update({where:{id:ph.id},data:{...p,verified:false,verificationNote:'Profile changed; re-verification required'}});await audit(req.auth!.userId,'PHARMACY_PROFILE_UPDATED','PHARMACY',ph.id);res.json(u);}catch(e){next(e)}});
app.get('/pharmacy/inventory',auth,roles(Role.PHARMACY),async(req:Req,res)=>{const ph=await db.pharmacy.findUnique({where:{userId:req.auth!.userId}});if(!ph)return res.status(404).json({error:'Pharmacy missing'});res.json(await db.inventory.findMany({where:{pharmacyId:ph.id},orderBy:{medicineName:'asc'}}));});
app.post('/pharmacy/inventory',auth,roles(Role.PHARMACY),async(req:Req,res,next)=>{try{const p=z.object({medicineName:z.string().trim().min(2).max(120),quantity:z.number().int().min(0).max(100000),unitPrice:z.number().nonnegative().max(100000)}).parse(req.body);const ph=await db.pharmacy.findUnique({where:{userId:req.auth!.userId}});if(!ph)return res.status(404).json({error:'Pharmacy missing'});const i=await db.inventory.upsert({where:{pharmacyId_medicineName:{pharmacyId:ph.id,medicineName:p.medicineName}},create:{pharmacyId:ph.id,...p},update:{quantity:p.quantity,unitPrice:p.unitPrice}});await audit(req.auth!.userId,'INVENTORY_UPDATED','INVENTORY',i.id);res.json(i);}catch(e){next(e)}});
app.delete('/pharmacy/inventory/:id',auth,roles(Role.PHARMACY),async(req:Req,res)=>{const ph=await db.pharmacy.findUnique({where:{userId:req.auth!.userId}});if(!ph)return res.status(404).json({error:'Pharmacy missing'});const i=await db.inventory.findFirst({where:{id:req.params.id,pharmacyId:ph.id}});if(!i)return res.status(404).json({error:'Inventory item not found'});await db.inventory.delete({where:{id:i.id}});await audit(req.auth!.userId,'INVENTORY_DELETED','INVENTORY',i.id);res.status(204).send();});
app.get('/pharmacy/requests',auth,roles(Role.PHARMACY),async(req:Req,res)=>{await expire();const ph=await db.pharmacy.findUnique({where:{userId:req.auth!.userId}});if(!ph)return res.status(404).json({error:'Pharmacy missing'});const rs=await db.medicineRequest.findMany({where:{status:RequestStatus.OPEN,expiresAt:{gt:new Date()},lat:{gte:-90}},include:{medicine:true,user:{select:{name:true}},responses:{where:{pharmacyId:ph.id}}},orderBy:{createdAt:'desc'},take:100});const nearby=rs.filter(r=>distanceKm(r.lat,r.lng,ph.lat,ph.lng)<=REQUEST_RADIUS_KM);res.json(nearby);});
app.post('/pharmacy/requests/:id/respond',auth,roles(Role.PHARMACY),async(req:Req,res,next)=>{try{const p=z.object({status:z.nativeEnum(ResponseStatus),price:z.number().nonnegative().max(100000).optional(),note:z.string().max(300).optional()}).parse(req.body);const ph=await db.pharmacy.findUnique({where:{userId:req.auth!.userId}});if(!ph)return res.status(404).json({error:'Pharmacy missing'});if(!ph.verified)return res.status(403).json({error:'Pharmacy is not verified'});const r=await db.medicineRequest.findUnique({where:{id:req.params.id},include:{medicine:true}});if(!r||r.status!==RequestStatus.OPEN||r.expiresAt<new Date())return res.status(400).json({error:'Request is no longer open'});if(distanceKm(r.lat,r.lng,ph.lat,ph.lng)>REQUEST_RADIUS_KM)return res.status(403).json({error:'Request is outside service radius'});if(p.status===ResponseStatus.AVAILABLE){const inv=await db.inventory.findUnique({where:{pharmacyId_medicineName:{pharmacyId:ph.id,medicineName:r.medicine.name}}});if(!inv||inv.quantity<r.quantity)return res.status(400).json({error:'Insufficient inventory'});if(p.price==null)p.price=inv.unitPrice;}const response=await db.availabilityResponse.upsert({where:{requestId_pharmacyId:{requestId:r.id,pharmacyId:ph.id}},create:{requestId:r.id,pharmacyId:ph.id,...p},update:p});await notify(r.userId,'Pharmacy response',`${ph.name} responded ${p.status.toLowerCase()}.`,{requestId:r.id,pharmacyId:ph.id});await audit(req.auth!.userId,'REQUEST_RESPONDED','REQUEST',r.id,{status:p.status});res.json(response);}catch(e){next(e)}});

app.post('/reservations',auth,roles(Role.PATIENT),async(req:Req,res,next)=>{try{await expire();const p=z.object({requestId:id,pharmacyId:id}).parse(req.body);const result=await db.$transaction(async tx=>{const r=await tx.medicineRequest.findFirst({where:{id:p.requestId,userId:req.auth!.userId,status:RequestStatus.OPEN,expiresAt:{gt:new Date()}}});if(!r)throw new Error('Request is not open');const response=await tx.availabilityResponse.findUnique({where:{requestId_pharmacyId:{requestId:r.id,pharmacyId:p.pharmacyId}},include:{pharmacy:true}});if(!response||response.status!==ResponseStatus.AVAILABLE||response.price==null)throw new Error('Pharmacy has not confirmed availability');const ph=response.pharmacy;if(!ph.verified)throw new Error('Pharmacy is not verified');const existing=await tx.reservation.findFirst({where:{requestId:r.id,status:ReservationStatus.ACTIVE}});if(existing)throw new Error('Request already reserved');const medicine=await tx.medicine.findUnique({where:{id:r.medicineId}});if(!medicine)throw new Error('Medicine not found');const inv=await tx.inventory.findUnique({where:{pharmacyId_medicineName:{pharmacyId:ph.id,medicineName:medicine.name}}});if(!inv||inv.quantity<r.quantity)throw new Error('Inventory is no longer available');const dec=await tx.inventory.updateMany({where:{id:inv.id,quantity:{gte:r.quantity}},data:{quantity:{decrement:r.quantity}}});if(dec.count!==1)throw new Error('Inventory changed; please retry');const reservation=await tx.reservation.create({data:{requestId:r.id,pharmacyId:ph.id,userId:req.auth!.userId,quantity:r.quantity,unitPrice:response.price,totalPrice:response.price*r.quantity,expiresAt:new Date(Date.now()+RESERVATION_TTL_HOURS*3600000),activeKey:`${r.id}:ACTIVE`}});await tx.medicineRequest.update({where:{id:r.id},data:{status:RequestStatus.FULFILLED,activeKey:null}});return {reservation,pharmacy:ph};});await notify(req.auth!.userId,'Reservation confirmed',`Your medicine is reserved for ${RESERVATION_TTL_HOURS} hours.`);await audit(req.auth!.userId,'RESERVATION_CREATED','RESERVATION',result.reservation.id,{quantity:result.reservation.quantity,totalPrice:result.reservation.totalPrice});res.status(201).json(result);}catch(e:any){res.status(400).json({error:e?.message??'Could not create reservation'});}});
app.get('/reservations',auth,roles(Role.PATIENT),async(req:Req,res)=>{await expire();res.json(await db.reservation.findMany({where:{userId:req.auth!.userId},include:{pharmacy:true,request:{include:{medicine:true}}},orderBy:{createdAt:'desc'},take:100}));});
app.get('/pharmacy/reservations',auth,roles(Role.PHARMACY),async(req:Req,res)=>{await expire();const ph=await db.pharmacy.findUnique({where:{userId:req.auth!.userId}});if(!ph)return res.status(404).json({error:'Pharmacy missing'});res.json(await db.reservation.findMany({where:{pharmacyId:ph.id},include:{request:{include:{medicine:true},},user:{select:{name:true,phone:true}}},orderBy:{createdAt:'desc'},take:100}));});
app.post('/reservations/:id/cancel',auth,roles(Role.PATIENT),async(req:Req,res,next)=>{try{const result=await db.$transaction(async tx=>{const r=await tx.reservation.findFirst({where:{id:req.params.id,userId:req.auth!.userId}});if(!r)throw new Error('Reservation not found');if(r.status!==ReservationStatus.ACTIVE)throw new Error('Reservation is not active');await restoreStock(tx,r);const updated=await tx.reservation.update({where:{id:r.id},data:{status:ReservationStatus.CANCELLED,activeKey:null}});const reqRow=await tx.medicineRequest.findUnique({where:{id:r.requestId}});if(reqRow&&reqRow.expiresAt>new Date())await tx.medicineRequest.update({where:{id:reqRow.id},data:{status:RequestStatus.OPEN,activeKey:`${reqRow.userId}:${reqRow.medicineId}`}});return updated;});await audit(req.auth!.userId,'RESERVATION_CANCELLED','RESERVATION',result.id);res.json(result);}catch(e:any){res.status(400).json({error:e.message});}});
app.post('/reservations/:id/pickup',auth,roles(Role.PHARMACY),async(req:Req,res,next)=>{try{const result=await db.$transaction(async tx=>{const r=await tx.reservation.findUnique({where:{id:req.params.id},include:{request:{include:{medicine:true}},pharmacy:true}});if(!r)throw new Error('Reservation not found');if(req.auth!.role===Role.PHARMACY){const ph=await tx.pharmacy.findUnique({where:{userId:req.auth!.userId}});if(!ph||ph.id!==r.pharmacyId||!ph.verified)throw new Error('Forbidden');}if(r.status!==ReservationStatus.ACTIVE)throw new Error('Reservation is not active');const med=await tx.medicine.findUnique({where:{id:r.request.medicineId}});if(!med)throw new Error('Patient medicine not found');const newRemaining=med.remaining+r.quantity;const newQuantity=med.quantity+r.quantity;const newNextRefillDate=new Date(Date.now()+daysRemaining(newRemaining,med.dosesPerDay)*86400000);await tx.medicine.update({where:{id:med.id},data:{remaining:newRemaining,quantity:newQuantity,nextRefillDate:newNextRefillDate}});const out=await tx.reservation.update({where:{id:r.id},data:{status:ReservationStatus.PICKED_UP,pickedUpAt:new Date(),activeKey:null}});return {reservation:out};});await notify(result.reservation.userId,'Pickup completed','Your medicine pickup has been recorded.');await audit(req.auth!.userId,'RESERVATION_PICKED_UP','RESERVATION',result.reservation.id);res.json(result);}catch(e:any){res.status(e.message==='Forbidden'?403:400).json({error:e.message});}});

app.get('/notifications',auth,async(req:Req,res)=>{const ns=await db.notification.findMany({where:{userId:req.auth!.userId},orderBy:{createdAt:'desc'},take:100});res.json(ns);});
app.post('/notifications/:id/read',auth,async(req:Req,res)=>{const n=await db.notification.updateMany({where:{id:req.params.id,userId:req.auth!.userId},data:{readAt:new Date()}});if(n.count===0)return res.status(404).json({error:'Notification not found'});res.json({ok:true});});
app.post('/notifications/read-all',auth,async(req:Req,res)=>{await db.notification.updateMany({where:{userId:req.auth!.userId,readAt:null},data:{readAt:new Date()}});res.json({ok:true});});
app.post('/push-tokens',auth,async(req:Req,res,next)=>{try{const p=z.object({token:z.string().min(10).max(500),platform:z.enum(['ios','android','web'])}).parse(req.body);const t=await db.pushToken.upsert({where:{token:p.token},create:{userId:req.auth!.userId,...p},update:{userId:req.auth!.userId,platform:p.platform}});res.json(t);}catch(e){next(e)}});

app.get('/admin/stats',auth,roles(Role.ADMIN),async(_req,res)=>res.json({users:await db.user.count(),patients:await db.user.count({where:{role:Role.PATIENT}}),pharmacies:await db.pharmacy.count(),verifiedPharmacies:await db.pharmacy.count({where:{verified:true}}),openRequests:await db.medicineRequest.count({where:{status:RequestStatus.OPEN}}),activeReservations:await db.reservation.count({where:{status:ReservationStatus.ACTIVE}})}));
app.get('/admin/pharmacies',auth,roles(Role.ADMIN),async(_req,res)=>res.json(await db.pharmacy.findMany({include:{user:{select:{id:true,name:true,phone:true,active:true}},_count:{select:{responses:true,reservations:true,inventory:true}}},orderBy:{verified:'asc'}})));
app.patch('/admin/pharmacies/:id/verify',auth,roles(Role.ADMIN),async(req:Req,res,next)=>{try{const p=z.object({verified:z.boolean(),note:z.string().max(500).optional()}).parse(req.body);const existing=await db.pharmacy.findUnique({where:{id:req.params.id}});if(!existing)return res.status(404).json({error:'Pharmacy not found'});if(p.verified&&(!existing.name.trim()||!existing.address.trim()||!Number.isFinite(existing.lat)||!Number.isFinite(existing.lng)))return res.status(400).json({error:'Pharmacy profile is incomplete'});const ph=await db.pharmacy.update({where:{id:req.params.id},data:{verified:p.verified,verificationNote:p.note??null}});await notify(ph.userId,p.verified?'Pharmacy verified':'Verification updated',p.verified?'Your pharmacy is now verified.':'Your pharmacy verification status was changed.');await audit(req.auth!.userId,p.verified?'PHARMACY_VERIFIED':'PHARMACY_UNVERIFIED','PHARMACY',ph.id,{note:p.note});res.json(ph);}catch(e){next(e)}});
app.get('/admin/users',auth,roles(Role.ADMIN),async(_req,res)=>res.json(await db.user.findMany({select:{id:true,name:true,phone:true,role:true,active:true,createdAt:true,pharmacy:{select:{id:true,name:true,verified:true}}},orderBy:{createdAt:'desc'},take:200}))); 
app.patch('/admin/users/:id/status',auth,roles(Role.ADMIN),async(req:Req,res,next)=>{try{const p=z.object({active:z.boolean()}).parse(req.body);if(req.params.id===req.auth!.userId&&!p.active)return res.status(400).json({error:'You cannot disable your own admin account'});const u=await db.user.update({where:{id:req.params.id},data:{active:p.active}});if(!p.active)await db.session.updateMany({where:{userId:u.id},data:{revokedAt:new Date()}});await audit(req.auth!.userId,p.active?'USER_ENABLED':'USER_DISABLED','USER',u.id);res.json({id:u.id,active:u.active});}catch(e){next(e)}});
app.get('/admin/audit-logs', auth, roles(Role.ADMIN), async (_req, res) => {
  const logs = await db.auditLog.findMany({
    orderBy: { createdAt: 'desc' },
    take: 200,
    include: { actor: { select: { id: true, name: true, role: true } } }
  });
  res.json(logs);
});

// Competition-focused Premium features: RevenueCat entitlement is the source of truth on mobile; webhook syncs server access.
async function requireConsumerPremium(req: Req, res: express.Response, next: express.NextFunction) { const active=await db.subscription.findFirst({where:{userId:req.auth!.userId,plan:'CONSUMER_PREMIUM',status:{in:['TRIALING','ACTIVE']}}}); if(!active)return res.status(402).json({error:'Premium required'}); next(); }
app.get('/premium/status',auth,async(req:Req,res)=>{const sub=await db.subscription.findFirst({where:{userId:req.auth!.userId,plan:'CONSUMER_PREMIUM'},orderBy:{updatedAt:'desc'}});res.json({active:!!sub&&['TRIALING','ACTIVE'].includes(sub.status),subscription:sub});});
app.get('/premium/features',auth,async(_req,res)=>res.json({features:['unlimited_family_members','unlimited_medicines','caregiver_sharing','automatic_refill_preparation','multiple_pharmacies','refill_history','advanced_reminders','priority_refill_request','travel_mode']}));
app.get('/family',auth,requireConsumerPremium,async(req:Req,res)=>res.json(await db.familyMember.findMany({where:{ownerId:req.auth!.userId},include:{member:{select:{id:true,name:true,phone:true}}}})));
app.post('/family',auth,requireConsumerPremium,async(req:Req,res,next)=>{try{const p=z.object({memberId:id,role:z.nativeEnum(FamilyRole)}).parse(req.body);if(p.memberId===req.auth!.userId)return res.status(400).json({error:'Cannot add yourself'});const member=await db.user.findUnique({where:{id:p.memberId}});if(!member)return res.status(404).json({error:'User not found'});const row=await db.familyMember.create({data:{ownerId:req.auth!.userId,memberId:p.memberId,role:p.role}});await notify(member.id,'Family sharing','You were added to a MedBridge family account.');res.status(201).json(row);}catch(e){next(e);}});
app.delete('/family/:id',auth,requireConsumerPremium,async(req:Req,res)=>{await db.familyMember.deleteMany({where:{id:req.params.id,ownerId:req.auth!.userId}});res.status(204).send();});
app.post('/medicines/:id/prepare-refill',auth,roles(Role.PATIENT),requireConsumerPremium,async(req:Req,res,next)=>{try{const m=await db.medicine.findFirst({where:{id:req.params.id,userId:req.auth!.userId}});if(!m)return res.status(404).json({error:'Medicine not found'});res.json({medicineId:m.id,quantity:m.quantity,prepared:true,message:'Refill request is ready. Review and send when you are ready.'});}catch(e){next(e);}});
app.post('/reminders',auth,roles(Role.PATIENT),async(req:Req,res,next)=>{try{const p=z.object({medicineId:id,hour:z.number().int().min(0).max(23),minute:z.number().int().min(0).max(59),advanced:z.boolean().default(false),timezone:z.string().min(1).max(80).default('Asia/Kolkata')}).parse(req.body);const m=await db.medicine.findFirst({where:{id:p.medicineId,userId:req.auth!.userId}});if(!m)return res.status(404).json({error:'Medicine not found'});if(p.advanced){const premium=await db.subscription.findFirst({where:{userId:req.auth!.userId,plan:'CONSUMER_PREMIUM',status:{in:['TRIALING','ACTIVE']}}});if(!premium)return res.status(402).json({error:'Premium required'});}res.status(201).json(await db.reminder.create({data:{...p,userId:req.auth!.userId}}));}catch(e){next(e);}});
app.put('/travel-mode',auth,roles(Role.PATIENT),requireConsumerPremium,async(req:Req,res,next)=>{try{const p=z.object({enabled:z.boolean(),startDate:z.coerce.date().optional(),endDate:z.coerce.date().optional(),timezone:z.string().max(80).optional(),notes:z.string().max(300).optional()}).parse(req.body);res.json(await db.travelMode.upsert({where:{userId:req.auth!.userId},create:{userId:req.auth!.userId,...p},update:p}));}catch(e){next(e);}});
const s3=new S3Client({region:process.env.AWS_REGION});const BUCKET=process.env.AWS_S3_BUCKET||'';
app.post('/documents',auth,async(req:Req,res,next)=>{try{const p=z.object({type:z.enum(['PRESCRIPTION','PHARMACY_LICENSE']),originalName:z.string().min(1).max(200),mimeType:z.string().regex(/^(application\/pdf|image\/(jpeg|png|webp))$/),sizeBytes:z.number().int().positive().max(10000000)}).parse(req.body);if(req.auth!.role===Role.PATIENT&&p.type!=='PRESCRIPTION')return res.status(403).json({error:'Patients can upload prescriptions only'});if(req.auth!.role===Role.PHARMACY&&p.type!=='PHARMACY_LICENSE')return res.status(403).json({error:'Pharmacies can upload licenses only'});if(!BUCKET)return res.status(503).json({error:'File storage is not configured'});const key=`${req.auth!.userId}/${p.type}/${crypto.randomUUID()}-${p.originalName}`;const row=await db.userDocument.create({data:{userId:req.auth!.userId,type:p.type as any,storageKey:key,originalName:p.originalName,mimeType:p.mimeType,sizeBytes:p.sizeBytes}});res.status(201).json({document:row,uploadKey:key});}catch(e){next(e);}});
app.get('/documents/:id/url',auth,async(req:Req,res,next)=>{try{if(!BUCKET)return res.status(503).json({error:'File storage is not configured'});const d=await db.userDocument.findFirst({where:{id:req.params.id,userId:req.auth!.userId}});if(!d)return res.status(404).json({error:'Document not found'});const url=await getSignedUrl(s3,new GetObjectCommand({Bucket:BUCKET,Key:d.storageKey}),{expiresIn:Number(process.env.AWS_S3_PRESIGN_SECONDS||600)});res.json({url,expiresIn:Number(process.env.AWS_S3_PRESIGN_SECONDS||600)});}catch(e){next(e);}});
app.post('/webhooks/revenuecat',async(req,res,next)=>{try{const secret=req.headers['x-revenuecat-signature'];if(process.env.REVENUECAT_WEBHOOK_SECRET&&secret!==process.env.REVENUECAT_WEBHOOK_SECRET)return res.status(401).end();const event=req.body?.event;const appUserId=event?.app_user_id;if(!appUserId)return res.status(400).json({error:'Missing app user id'});const type=String(event?.type||'');const active=['INITIAL_PURCHASE','RENEWAL','UNCANCELLATION','NON_RENEWING_PURCHASE','SUBSCRIPTION_EXTENDED'].includes(type);const inactive=['CANCELLATION','EXPIRATION','BILLING_ISSUE'].includes(type);if(active||inactive){const user=await db.user.findUnique({where:{id:appUserId}});if(user){const providerId=event?.original_transaction_id||event?.transaction_id||`rc-${appUserId}`;await db.subscription.upsert({where:{providerSubscriptionId:providerId},create:{userId:user.id,plan:'CONSUMER_PREMIUM',status:active?'ACTIVE':'EXPIRED',provider:'revenuecat',providerCustomerId:appUserId,providerSubscriptionId:providerId,currentPeriodStart:event?.purchased_at_ms?new Date(Number(event.purchased_at_ms)):undefined,currentPeriodEnd:event?.expiration_at_ms?new Date(Number(event.expiration_at_ms)):undefined},update:{status:active?'ACTIVE':'EXPIRED',currentPeriodStart:event?.purchased_at_ms?new Date(Number(event.purchased_at_ms)):undefined,currentPeriodEnd:event?.expiration_at_ms?new Date(Number(event.expiration_at_ms)):undefined}});}}res.json({ok:true});}catch(e){next(e);}});
app.use((_req,res)=>res.status(404).json({error:'Route not found'}));

app.use((err:any,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{console.error(err);if(err instanceof z.ZodError)return res.status(400).json({error:'Invalid input',details:err.issues.map(i=>({path:i.path,message:i.message}))});if(err?.code==='P2002')return res.status(409).json({error:'Resource already exists'});res.status(500).json({error:'Internal server error'});});

let server: ReturnType<typeof app.listen> | undefined;
const shutdown=async()=>{await db.$disconnect();if(server)server.close(()=>process.exit(0));else process.exit(0);};
if(process.env.NODE_ENV !== 'test'){server=app.listen(PORT,()=>console.log(`MEDBRIDGE API listening on :${PORT}`));process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);}
export { app, db, distanceKm, daysRemaining };